diff -Naur a/Makefile b/Makefile
--- a/Makefile	2009-02-14 02:07:04.000000000 +0000
+++ b/Makefile	2012-06-03 10:42:01.000000000 +0000
@@ -23,8 +23,8 @@
 # Change this if you want to install somewhere else. In particular
 # you may wish to remove the middle "local/" part of the path.
 
-INSTALL_PLUGINS_DIR	=	/usr/local/lib/ladspa/
-INSTALL_LRDF_DIR	=	/usr/local/share/ladspa/rdf/
+INSTALL_PLUGINS_DIR	=	/usr/lib/ladspa/
+INSTALL_LRDF_DIR	=	/usr/share/ladspa/rdf/
 
 # NO EDITING below this line is required
 # if all you want to do is install and use the plugins.
@@ -63,10 +63,10 @@
 # OTHER TARGETS
 
 install: targets
-	-mkdir -p		$(INSTALL_PLUGINS_DIR)
-	cp *.so 		$(INSTALL_PLUGINS_DIR)
-	-mkdir -p		$(INSTALL_LRDF_DIR)
-	cp inv_plugins.rdf 	$(INSTALL_LRDF_DIR)
+	-mkdir -p		$(DESTDIR)$(INSTALL_PLUGINS_DIR)
+	cp *.so 		$(DESTDIR)$(INSTALL_PLUGINS_DIR)
+	-mkdir -p		$(DESTDIR)$(INSTALL_LRDF_DIR)
+	cp inv_plugins.rdf 	$(DESTDIR)$(INSTALL_LRDF_DIR)
 
 targets:	$(PLUGINS)
 
