diff -Naur a/Makefile b/Makefile
--- a/Makefile	2014-05-26 15:51:56.000000000 +0100
+++ b/Makefile	2016-07-14 13:21:38.120167671 +0100
@@ -23,8 +23,8 @@
 # Change this if you want to install somewhere else. In particular
 # you may wish to remove the middle "local/" part of the path.
 
-INSTALL_PLUGINS_DIR	=	/usr/local/lib/ladspa/
-INSTALL_LRDF_DIR	=	/usr/local/share/ladspa/rdf/
+INSTALL_PLUGINS_DIR	=	/usr/lib/ladspa/
+INSTALL_LRDF_DIR	=	/usr/share/ladspa/rdf/
 
 # NO EDITING below this line is required
 # if all you want to do is install and use the plugins.
@@ -56,11 +56,11 @@
 # OTHER TARGETS
 
 install: all
-	-mkdir -p          $(INSTALL_PLUGINS_DIR)
-	cp *.so            $(INSTALL_PLUGINS_DIR)
-	-mkdir -p          $(INSTALL_LRDF_DIR)
-	cp tap-plugins.rdf $(INSTALL_LRDF_DIR)
-	cp tap_reverb.rdf  $(INSTALL_LRDF_DIR)
+	-mkdir -p          $(DESTDIR)$(INSTALL_PLUGINS_DIR)
+	cp *.so            $(DESTDIR)$(INSTALL_PLUGINS_DIR)
+	-mkdir -p          $(DESTDIR)$(INSTALL_LRDF_DIR)
+	cp tap-plugins.rdf $(DESTDIR)$(INSTALL_LRDF_DIR)
+	cp tap_reverb.rdf  $(DESTDIR)$(INSTALL_LRDF_DIR)
 
 clean:
 	-rm -f *.so *.o *~
