.\" Comment for the sake of comment.
.TH SEPKG.CONF 5 "September 2011" Studioware 
.SH NAME
sepkg.conf \- sepkg(8) configuration file
.SH SYNOPSIS
.B /etc/sepkg/sepkg.conf
.SH DESCRIPTION
The
.I sepkg.conf
file is a resource for environment variables used by sepkg 
when getting SlackBuilds, fetching sources and outputting packages.

.SH VARIABLES
.IP SWVERSION
.B Mandatory!
The Studioware repo version to pull from.
.br
Default: SWVERSION=13.37
.IP SBSERVER
.B Optional.
The server from which you want to pull SlackBuild archives.
.br
Default: http://www.studioware.org/slackbuilds/$SWVERSION
.IP CACHEDIR
.B Optional.
Parent directory to cache downloaded files.
.br
Default: /var/cache/sepkg
.br
/$SWVERSION/ will be added automatically.
.P
The usual variables like OUTPUT, TMP etc. that are used in slackbuilds
are also legitimate here.
.SH "SEE ALSO"
.BR sepkg(8)
