#!/bin/sh

#{{{ Copyright
# Studioware package building script
# Copyright 2011 David Woodfall <dave@dawoodfall.net>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#}}}
#{{{ Init
init()
{
    APPNAME="sepkg"
    VERSION="4.2b1"
    CONFDIR=/etc/$APPNAME
    mkdir -p $CONFDIR
    CONF=$CONFDIR/$APPNAME.conf
    touch $CONF
    source $CONF 
    TMP=${TMP:-/tmp/se}
    OUTPUT=${OUTPUT:-/tmp}
    TMPROOT=$(mktemp -d -p $OUTPUT $APPNAME-XXXXXX) || exit
    trap "cleanupbad" HUP INT ABRT QUIT SEGV TERM KILL PIPE STOP TSTP
    QUEUE=$TMPROOT/queue
    TMPQ=$TMPROOT/tmp-queue
    PKGLIST=$TMPROOT/pkglist
    WGET="wget --no-check-certificate"
    UP="upgradepkg --reinstall --install-new"
    MAINURL="http://www.studioware.org"
    TOOLURL="$MAINURL/files/tools/$APPNAME"
    SBSERVER="$MAINURL/files/slackbuilds/$SWVERSION"
    CACHEDIR=/var/cache/$APPNAME/$SWVERSION
    mkdir -p $CACHEDIR
    FILELIST=$CACHEDIR/SLACKBUILDS.TXT
    ERR="0"
    STUDIOKEY="Studioware <info@studioware.org>"
    GPG="gpg --verify"
    CWD=$(pwd)
    if [ -z "$CHECKGPG" ]; then
        echo "CHECKGPG not set in $CONF..."
        echo "Setting to ON. You can change this later by editing $CONF"
        echo "CHECKGPG=ON" >> $CONF
        CHECKGPG="ON"
        echo -n "Press enter to continue"
        read <&1
    fi
}
#}}}
#{{{ Cleanup and exit
cleanup()
{
    rm -rf $TMPROOT
    exit 0
}
#}}}
#{{{ Cleanup and exit 1
cleanupbad()
{
    rm -rf $TMPROOT
    exit 1
}
#}}}
#{{{ Flags
getflags()
{
    if [ "$1" = "info" ]; then { info $2; cleanup; }; fi
    if [ "$1" = "-f" ]; then { info $2; cleanup; }; fi
    if [ "$1" = "update" ]; then { update; cleanup; }; fi
    if [ "$1" = "-u" ]; then { update; cleanup; }; fi
    if [ "$1" = "search" ]; then { search $2; cleanup; }; fi
    if [ "$1" = "-s" ]; then { search $2; cleanup; }; fi
    if [ "$1" = "build" ]; then { INSTALL=0; set_queue "$@"; cleanup; }; fi
    if [ "$1" = "-b" ]; then { INSTALL=0; set_queue "$@"; cleanup; }; fi
    if [ "$1" = "install" ]; then { INSTALL=1; set_queue "$@"; cleanup; }; fi
    if [ "$1" = "-i" ]; then { INSTALL=1; set_queue "$@"; cleanup; }; fi
    if [ "$1" = "delete-cache" ]; then { deletecache; cleanup; }; fi
    if [ "$1" = "latest" ]; then { latest; cleanup; }; fi
    if [ "$1" = "-l" ]; then { latest; cleanup; }; fi
    if [ "$1" = "read" ]; then { readme $2; cleanup; }; fi
    if [ "$1" = "-r" ]; then { readme $2; cleanup; }; fi
    if [ "$1" = "-q" ]; then { INSTALL=1; get_queue $2; cleanup; }; fi
    if [ "$1" = "queue" ]; then { INSTALL=1; get_queue $2; cleanup; }; fi
    if [ "$1" = "-h" ]; then {  usage; cleanup; }; fi
    if [ "$1" = "-v" ]; then { echo $APPNAME $VERSION; cleanup; }; fi
    if [ "$1" = "-g" ]; then { importgpg; cleanup; }; fi
    if [ "$1" = "gpg" ]; then { importgpg; cleanup; }; fi
}
#}}}
#{{{ Info
info()
{
    APP=$1
    
    if [ -z "$APP" ]; then
        echo "No application name specified!"
        cleanup
    fi

    if [ ! -r $FILELIST ]; then
        echo "No filelist found. Do you need to run sepkg -u?"
        cleanup
    fi

    CAT=$(grep -wi $APP $FILELIST | cut -d/ -f2)
    info="$(curl -s $SBSERVER/$CAT/$APP/$APP.info)"
    echo "$info"
}
#}}}
#{{{ Readme
readme()
{
    if [ -z "$1" ]; then
        echo "No application name specified!"
        cleanup
    fi

    file=$(grep -i $1.tar.gz $FILELIST | awk '{print $2}' | cut -d'/' -f1-3)/README
    shortname=$(echo $file | cut -d'/' -f5 | rev | cut -d- -f4- | rev)
    url=$SBSERVER/$file
    lynx -dump $url
    cleanup
}
#}}}
#{{{ Latest
latest()
{
    cd $TMPROOT
    
    LATEST=$(curl -s $TOOLURL/LATEST)
    REMVERS=$(echo $LATEST | cut -db -f1)
    REMBUILD=$(echo $LATEST | cut -db -f2)

    echo "Installed version: $VERSION. Latest version: $LATEST."

    if [ "$VERSION" != "$LATEST" ]; then
        echo -n "Newer version available. Download it? (Y/n) "
        read REPLY

        case "$REPLY" in
            'y'|'Y'|'')
                PKG=$APPNAME-$REMVERS-noarch-${REMBUILD}daw.txz
                ASC=$APPNAME-$REMVERS-noarch-${REMBUILD}daw.txz.asc
                MD5=$APPNAME-$REMVERS-noarch-${REMBUILD}daw.md5
                $WGET -q -O $PKG $TOOLURL/$PKG
                $WGET -q -O $MD5 $TOOLURL/$MD5
                $WGET -q -O $ASC $TOOLURL/$ASC

                echo "Package saved to $TMPROOT"
                echo "Checking md5... "

                md5sum -c $MD5

                if [ $? != 0 ]; then
                    cleanup
                fi

                if [ "$CHECKGPG" = "ON" ]; then
                    echo "Checking gpg..."
                    # try to surpress the authority warning...
                    GPGOUT=$($GPG $ASC $PKG 2>&1 | head -n2)

                    if [ -n "$(echo $GPGOUT | grep -i 'not found')" ]; then
                        echo "$GPGOUT"
                        echo "Did you import the Studioware key with 'studiopkg -g|gpg'?"
                        cleanup
                    elif [ -n "$(echo $GPGOUT | grep -i 'bad signature')" ]; then
                            echo "$GPGOUT"
                            cleanup
                    else
                        echo "$GPGOUT"
                    fi
                fi


                echo
                echo -n "Upgrade now? (Y/n) "
                read UREPLY

                case "$UREPLY" in
                    'y'|'Y'|'')
                        $UP $PKG
                        ;;
                    *)
                        cleanup
                        ;;
                esac
                ;;
            *)
                cleanup
                ;;
        esac
    fi
#    cd $TMPROOT
#    
#    LATEST=$(curl -s $TOOLURL/LATEST)
#    REMVERS=$(echo $LATEST | cut -db -f1)
#    REMBUILD=$(echo $LATEST | cut -db -f2)
#
#    echo "Installed version: $VERSION. Latest version: $LATEST."
#
#    if [ "$VERSION" != "$LATEST" ]; then
#        echo -n "Newer version available. Download it? (y/n) "
#        read REPLY
#
#        if [ "$REPLY" = "y" ]; then
#            PKG=$APPNAME-$REMVERS-noarch-${REMBUILD}daw.txz
#            MD5=$APPNAME-$REMVERS-noarch-${REMBUILD}daw.md5
#            $WGET -q -O $PKG $TOOLURL/$PKG
#            $WGET -q -O $MD5 $TOOLURL/$MD5
#
#            echo "Package saved to $TMPROOT"
#            echo "Checking md5... "
#
#            md5sum -c $MD5
#
#            if [ $? != 0 ]; then
#                cleanup
#            fi
#
#            echo
#            echo -n "Upgrade now? (y/n) "
#            read REPLY
#            if [ "$REPLY" = "y" ]; then
#                $UP $PKG
#            fi
#        fi
#    fi
}
# }}}
#{{{ Usage
usage()
{
cat << EOF
$APPNAME $VERSION

Options

$APPNAME info/-f package1 - read info file
$APPNAME build/-b package1, package2 ... - build packages
$APPNAME delete-cache - delete all cached files
$APPNAME install/-i package1, package2 ... - build & install packages
$APPNAME install/-i < <queuefile> - install packages from file
$APPNAME latest/-l - checks for newer version of $APPNAME
$APPNAME read/-r <package> - download and print readme (needs lynx)
$APPNAME search/-s - search for package name or part name
$APPNAME update/-u - syncs with file server
$APPNAME queue/-q - download and install queue from file server
$APPNAME -h - help
$APPNAME -v - give version and exit

Files

/etc/$APPNAME/$APPNAME.conf

This file contains the mirror URL and should be edited for 32bit or 64bit.
EOF
}
#}}}
#{{{ Update
update()
{   
    cd $CACHEDIR || cleanup
    $WGET -O SLACKBUILDS.TXT $SBSERVER/SLACKBUILDS.TXT
    cleanup
}
#}}}
#{{{ Get Queue
get_queue()
{
    cd $CACHEDIR || { echo "No cache exists! Did you run update?"; cleanup; }

    if [ ! -r $FILELIST ]; then { echo "No filelist! Did you run update?"; \
        cleanup; } fi

    cd $TMPROOT || cleanup

    case "$1" in
        'audio'|'video'|'photo'|'full')
            curl -fs $SBSERVER/queues/$1.sqf > $QUEUE
            ;;

        *)
            CAT=$(grep -i /$1.tar.gz$ $FILELIST | cut -d/ -f2-4)
            APP=$(grep -i /$1.tar.gz$ $FILELIST | cut -d/ -f4)
            curl -fs $SBSERVER/$CAT/$APP.sqf > $QUEUE 

            if [ $? != 0 ]; then
                if [ ! -r $CWD/$1 ] && [ ! -r $1 ]; then
                    echo "Queue $1 not found."
                    cleanup
                else
                    if [ -r "$CWD/$1" ]; then
                        cat $CWD/$1 > $QUEUE
                    else
                        cat $1 > $QUEUE
                    fi

                fi
            fi
            ;;
    esac

    listpkgs
}
#}}}
#{{{ Set Queue
set_queue()
{
    cd $CACHEDIR || { echo "No cache exists! Did you run update?"; cleanup; }
    if [ ! -r $FILELIST ]; then { echo "No filelist! Did you run update?"; \
        cleanup; } fi

    cd $TMPROOT || cleanup
    shift

    cl=$*
    if [ -z "$cl" ]; then
        cat /dev/stdin | sed 's/,/\n/g;/^$/d' > $QUEUE 
    else
        echo $cl | sed 's/,/\n/g;/^$/d' > $QUEUE
    fi

    listpkgs
}
#}}}
#{{{ Make queue
make_queue()
{
    cd $TMPROOT
    let CNT=1

    while read line
    do
        TOP=$(head -n $((CNT-1)) $TMPQ)

        if [ -n "$TOP" ]; then
            echo "$TOP" > $TMPQ
        fi

        case "$line" in
            'audio'|'video'|'photo'|'full')
                $WGET -O $line.sqf $SBSERVER/queues/$line.sqf
                SWAP=$(cat $line.sqf)
                echo "$SWAP" >> $TMPQ
                let CNT=$(wc -l $TMPQ | awk '{print $1}')+1
                unset SWAP
                ;;

            *)
                # subqueue
                if [ -z "$(echo $line | cut -d@ -f1)" ] && [ -n "$line" ]; then
                    SUB=$(echo $line | cut -d@ -f2)

                    if [ -n "$SUB" ]; then
                        if [ ! -r $CWD/$SUB.sqf ] && [ ! -r $SUB.sqf ]; then
                            CAT=$(grep -i /$SUB.tar.gz$ $FILELIST | cut \
                            -d/ -f2-4)

                            if [ -n "$CAT" ]; then
                                $WGET -O $SUB.sqf $SBSERVER/$CAT/$SUB.sqf
                            else
                                echo "$SUB.sqf not found."
                                cleanup
                            fi
                            if [ $? != 0 ]; then
                                echo "$SUB.sqf not found."
                                cleanup
                            fi
                        else
                            if [ -r $CWD/$SUB.sqf ]; then
                                cat $CWD/$SUB.sqf > $SUB.sqf
                            fi
                        fi

                        if [ -r $SUB.sqf ]; then
                            SWAP=$(cat $SUB.sqf)
                            echo "$SWAP" >> $TMPQ
                            let CNT=$(wc -l $TMPQ | awk '{print $1}')+1
                            unset SWAP
                        fi
                    fi
                else
                    echo $line >> $TMPQ
                    let CNT=$((CNT+1))
                fi
                ;;
        esac
    done < $1
}
#}}}
#{{{ List Packages
listpkgs()
{
    exec <&1
    unset pkgs
    unset INSTALLLIST
    unset MISSING

    echo "Building queue..."

    while true
    do
        if [ -n "$(grep @ $QUEUE)" ]; then
            echo -n > $TMPQ
            make_queue $QUEUE
            cat $TMPQ > $QUEUE
        else
            break
        fi
    done

    echo -n > $TMPQ

    while read line
    do
        if [ ! $(grep -x $line $TMPQ) ]; then
            echo $line >> $TMPQ
        fi
    done < $QUEUE

    cat $TMPQ > $QUEUE

    while read line
    do
        name=$(echo $line | awk '{print $1}')
        pkg=$(grep /$name.tar.gz $FILELIST | cut -d'/' -f5)

        if [ -n "$pkg" ]; then
            PKGS=$PKGS" "$pkg
        else
            MISSING=$name" "$MISSING
        fi
    done < $QUEUE

    if [ -z "$PKGS" ]; then
        echo "The following applications could not be found:"
        echo "$MISSING"
        cleanup
    fi

    for i in $PKGS
    do
        shortname=$(echo $i | cut -d'.' -f1)
        if [ -n "$i" ]; then
            INSTALLLIST=$INSTALLLIST" "$i" "$shortname" ""on "
        fi
    done

    if [ -z "$INSTALLLIST" ]; then cleanup; fi

    dialog --separate-output --title install --backtitle "$APPNAME $VERSION" \
        --help-button --help-label "Clear Inst'd" --help-status \
        --checklist "Choose packages to install:" \
        19 70 13 $INSTALLLIST 2>$PKGLIST
    
    CHOICE=$?

    if [ $CHOICE -eq 2 ] && $(sed -i 's%^HELP %%g' $PKGLIST); then
        clear_installed
        listpkgs
    fi

    if [ $CHOICE -ne 0 ]; then cleanup; fi
    if [ -z "$(cat $PKGLIST)" ]; then cleanup; fi

    installpkgs
}
#}}}
#{{{ Clear Installed
clear_installed()
{
    while read newpkg
    do
        for o in $(ls /var/log/packages/$newpkg* 2>/dev/null)
        do
            oldpkg=$(echo $o | cut -d/ -f5 | rev | cut -d- -f4- | rev)

            if [ -n "$(echo $oldpkg | grep upgraded)" ]; then
                oldpkg="NULL"
            fi

            if [ "$newpkg" == "$oldpkg" ]; then
                sed -i "/$newpkg$/d" $QUEUE
            fi
        done
    done < $QUEUE

    if [ $(wc -l $QUEUE | awk '{print $1}') = "0" ]; then
        echo "All packages are already installed."
        cleanup
    fi
}
#}}}
#{{{ Install Packages
installpkgs()
{
    cd $TMPROOT || cleanup
    unset pkgs

    for i in $(cat $PKGLIST)
    do
        pkgs=$pkgs" "$(grep -wie "\/.*\/$i" $FILELIST | awk '{print $2}')
    done

    for i in $pkgs
    do
        if [ -n "$i" ]; then
            b=$(basename $i .tar.gz)
            $WGET -c -O $b.tar.gz $SBSERVER/$i
            tar xf $b.tar.gz
            (
            cd $b
            source ./$b.info        
            unset loop
            MD5SUM=($MD5SUM)

            for D in $DOWNLOAD
            do
                LOCAL=$(basename $D)
                MD5=${MD5SUM[loop]}
                unset MD5MATCH

                while [ -z "$MD5MATCH" ]
                do
                    if [ ! -r $CACHEDIR/$LOCAL ]; then
                        $WGET -c -O $CACHEDIR/$LOCAL $D
                    fi
                    
                    ln -sf $CACHEDIR/$LOCAL $LOCAL

                    if [ "$(md5sum $LOCAL | awk '{print $1}')" != "$MD5" ]; then 
                        echo "Checksums don't match."
                        echo -n "(A)bort (C)ontinue (R)edownload "
                        read ANS
                        if [[ "$ANS" = [rR] ]]; then 
                            rm -r $CACHEDIR/$LOCAL
                        elif [[ "$ANS" = [cC] ]]; then
                            break
                        else exit 1
                        fi
                    else MD5MATCH=1
                    fi
                done
                let loop=$loop+1
            done

            options=$(grep -x $b $QUEUE | cut -f2- | sed "s/$b//")
            eval $options source ./$b.SlackBuild
            if [ "$INSTALL" = "1" ]; then
                $UP $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
            fi
            if [ -n "$ARCHIVE" ]; then
                mv $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz} $ARCHIVE
            fi
            )
            ERR=$?

            if [ "$ERR" != "0" ]; then
                break
            fi
        fi
    done

    if [ "$ERR" != "0" ]; then
        cleanupbad
    fi

    cleanup
}
#}}}
#{{{ Search
search()
{
    cd $CACHEDIR || { echo "No cache exists! Did you run update?"; cleanup; }
    if [ ! -r $FILELIST ]; then { echo "No filelist! Did you run update?"; \
        cleanup; } fi

    inrepo=$(grep -i $1 $FILELIST | awk '{print $2}')

    if [ -n "$inrepo" ]; then
        for g in $inrepo
        do
            shortname=$(echo $g | cut -d'/' -f3)
            dir=$(echo $g | cut -d'/' -f2)
            installed=$(ls /var/log/packages/$shortname-[0-9]* 2>/dev/null)

            if [ -e "$installed" ]; then 
                version=$(echo $installed | cut -d'/' -f5 | rev | cut -d- -f3 \
                    | rev)
                echo "[Installed]	$dir/$(echo $installed | cut -d'/' -f5)"
            else echo "[Not Installed]	$dir/$shortname"
            fi
        done
    fi
}
#}}}
#{{{ Import gpg key
importgpg()
{
    # ripped from slackpkg
    if ! [ -e ~/.gnupg ]; then
        mkdir ~/.gnupg
    fi

    cd $TMPROOT || cleanup
    $WGET -O gpgkey ${PKGSERVER}/GPG-KEY || cleanup
    gpg --yes --batch --delete-key "$STUDIOKEY"
    gpg --import gpgkey
    echo "Studioware GPG key added"
    cleanup
}
#}}}
#{{{ Delete Cache !DANGER WILL ROBINSON!
deletecache()
{
    rm -r $CACHEDIR 
    mkdir -p $CACHEDIR 
    echo "Cache Deleted"
    cleanup
}
#}}}
init
getflags "$@"
